### ISSUE TITLE
With KissAnime gone, and 9anime being annoying, work to support additional source sites.

### ISSUE THREAD

**Issue by MohammedADev** [Wicloz/AnimeSentinel#12]
Hey is the website down?

**Comment by Wicloz** [comment]
It's not down but it definitely doesn't work right now.

**Comment by MohammedADev** [comment]
oh ok

**Comment by Wicloz** [comment]
As in, you cant watch any episodes due to changes on 9anime's end as well as the loss of KissAnime.

**Comment by MohammedADev** [comment]
Why not fetch from gogoanime?

**Comment by Wicloz** [comment]
Other sources such as gogoanime are supported, but writing the code is several days of work, and I have little free time ATM. I'll leave this issue open and work on expanding this in the future (think Christmas holiday).

**Comment by MohammedADev** [comment]
Ok thank you I'll look forward to it

**Comment by MohammedADev** [comment]
> Other sources such as gogoanime are supported, but writing the code is several days of work, and I have little free time ATM. I'll leave this issue open and work on expanding this in the future (think Christmas holiday).

any updates?
