### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by MohammedADev** [Wicloz/AnimeSentinel#14]
Email verification is not working.
![image](https://user-images.githubusercontent.com/40725969/106925223-bc144400-66c4-11eb-9982-ea9938c45eaf.png)

**Comment by Wicloz** [comment]
Thanks for letting me know, AS was not able to send emails. This is a mailserver issue and not due to AS. Should be fixed now, let me know if it works.

**Comment by MohammedADev** [comment]
Still doesn’t work for me

**Comment by MohammedADev** [comment]
> Thanks for letting me know, AS was not able to send emails. This is a mailserver issue and not due to AS. Should be fixed now, let me know if it works.

Oh nvm it works now thank you

**Comment by MohammedADev** [comment]
> Thanks for letting me know, AS was not able to send emails. This is a mailserver issue and not due to AS. Should be fixed now, let me know if it works.

Also i was thinking of your api problem. Maybe you can use this? https://github.com/ICEPrey/animexninja-api
