### ISSUE TITLE
Change the url

### ISSUE THREAD

**Issue by carvalab** [Wicloz/AnimeSentinel#22]
Please change anime.wilcodeboer.me for https://anime.wicloz.rocks
anime.wilcodeboer.me
![Captura de Pantalla 2022-01-25 a la(s) 14 55 00](https://user-images.githubusercontent.com/1446654/151032351-abc07d48-9b3d-49b3-a4b9-e6db046ce598.png)
 https://anime.wicloz.rocks
![Captura de Pantalla 2022-01-25 a la(s) 14 55 13](https://user-images.githubusercontent.com/1446654/151032376-c453acc3-67a0-4b56-a91b-9c3d1ad599cc.png)

**Comment by Wicloz** [comment]
I knew I forgot something, thanks.
