### ISSUE TITLE
Not working. It doesn't scrape.

### ISSUE THREAD

**Issue by dhernandez0798** [Wicloz/AnimeSentinel#7]
Hello. I've installed it, although I've had some problems with migrations. Finally it worked, but when I make a search, it throws me this error:

>  QueryException in Connection.php line 764:
> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'offset 0' at line 1 (SQL: select * from `shows` where (`type` in (tv, ona, ova, movie, special, unknown) or `type` is null) and (1 = 0 or (`genres` like %"Action"%) or (`genres` like %"Adventure"%) or (`genres` like %"Cars"%) or (`genres` like %"Comedy"%) or (`genres` like %"Dementia"%) or (`genres` like %"Demons"%) or (`genres` like %"Drama"%) or (`genres` like %"Ecchi"%) or (`genres` like %"Fantasy"%) or (`genres` like %"Game"%) or (`genres` like %"Harem"%) or (`genres` like %"Historical"%) or (`genres` like %"Horror"%) or (`genres` like %"Josei"%) or (`genres` like %"Kids"%) or (`genres` like %"Magic"%) or (`genres` like %"Martial Arts"%) or (`genres` like %"Mecha"%) or (`genres` like %"Military"%) or (`genres` like %"Music"%) or (`genres` like %"Mystery"%) or (`genres` like %"Parody"%) or (`genres` like %"Police"%) or (`genres` like %"Psychological"%) or (`genres` like %"Romance"%) or (`genres` like %"Samurai"%) or (`genres` like %"School"%) or (`genres` like %"Sci-Fi"%) or (`genres` like %"Seinen"%) or (`genres` like %"Shoujo"%) or (`genres` like %"Shoujo Ai"%) or (`genres` like %"Shounen"%) or (`genres` like %"Shounen Ai"%) or (`genres` like %"Slice of Life"%) or (`genres` like %"Space"%) or (`genres` like %"Sports"%) or (`genres` like %"Super Power"%) or (`genres` like %"Supernatural"%) or (`genres` like %"Thriller"%) or (`genres` like %"Vampire"%) or (`genres` like %"Yaoi"%) or (`genres` like %"Yuri"%) or `genres` = []) and (`rating` in (G, PG, PG-13, R, R+, Unknown) or `rating` is null) and ((`alts` like %"sdfsdf"%) or (`alts` like %"%sdfsdf%"%) or (`alts` like %"%sdfsdf%"%) or (`alts` like %"%sdfsdf%"%)) order by `title` asc offset 0)
> 

Like if the query were malformed. In the DB, I don't have any row in videos. Where is the problem? Everything else works fine.

PD: also, a good guide about the set-up would be great :)

**Comment by Wicloz** [comment]
This pertains to legacy code. Issue no longer present in meteor branch. Closing.
